
[text_to_sql]
model_id = "qwen3-30b-a3b"
temperature = 0.01
max_completion_tokens = 32000
reload_schema = false

[llm]
base_url = ""
models = ["qwen3-coder-30b-a3b-instruct", "qwen3-30b-a3b"]
api_key = "llmstudio"
temperature = 0.01
max_completion_tokens = 32000
read_timeout = 240000
provider = "kimi"


[kimi]
api_key = ""
base_url = "https://api.moonshot.ai/v1"
models = ["kimi-k2-thinking"]
temperature = 0.01
max_completion_tokens = 32000
read_timeout = 240000

[agents]
tavily_api_key = ""
exa_api_key = ""
exa_team_id = ""

[google]
api_key = ""
search_engine_id = ""
