
[text_to_sql]
model_id = "qwen3-30b-a3b"
temperature = 0.01
max_completion_tokens = 32000
reload_schema = false

[llm]
base_url = "http://192.168.1.95:1234/v1/"
models = ["qwen3-coder-30b-a3b-instruct", "qwen3-30b-a3b"]
api_key = "llmstudio"
temperature = 0.01
max_completion_tokens = 32000
read_timeout = 240000
provider = "kimi"


[kimi]
api_key = "sk-nQAG77Aja7Xawyzp04hMoNSMb6XJHENNsqOQ9loauIOvHFJk"
base_url = "https://api.moonshot.ai/v1"
models = ["kimi-k2-thinking"]
temperature = 0.01
max_completion_tokens = 32000
read_timeout = 240000

[agents]
tavily_api_key = "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"
exa_api_key = "3451c61e-b7bd-483c-a1d4-2b6886782a13"
exa_team_id = "cmfu4fcbi0002efebwxp9n89m"

[google]
api_key = "AIzaSyBlxgJFjJ12kIiieN8C378bH55PDRm1e0w"
search_engine_id = "97ac12ae3815a46a9"
